In [2]:
import numpy as np

In [128]:
X = np.array([[1,2,0.5],[0,1,1]])
y = np.array([1,2])
from sklearn.naive_bayes import MultinomialNB
clf = MultinomialNB(alpha = 1) 
clf.fit(X, y)

MultinomialNB(alpha=1, class_prior=None, fit_prior=True)

[[ln(2/6.5),ln(3/6.5), ln(1.5/6.5)],
 [ln(1/5), ln(2/5), ln(2/5)]]

In [129]:
clf.feature_log_prob_

array([[-1.178655  , -0.77318989, -1.46633707],
       [-1.60943791, -0.91629073, -0.91629073]])

[ln(1/2), ln(1/2)]

In [130]:
clf.class_log_prior_

array([-0.69314718, -0.69314718])

In [125]:
test = np.array([[1,0,0],[0,1,0],[0,0,1],[0,1,1],[1,0,1],[1,1,0], [1,1,1]])
print(clf.predict(test))

[1 1 2 2 2 1 1]


In [126]:
res = np.matmul(test, clf.feature_log_prob_.T) + clf.class_log_prior_
res

array([[-1.87180218, -2.30258509],
       [-1.46633707, -1.60943791],
       [-2.15948425, -1.60943791],
       [-2.93267414, -2.52572864],
       [-3.33813925, -3.21887582],
       [-2.64499207, -3.21887582],
       [-4.11132913, -4.13516656]])

In [127]:
res.argmax(axis=1) + 1

array([1, 1, 2, 2, 2, 1, 1])

In [66]:
def predict_compare(clf, test_data):
    
    print("Prediction is: ")
    print(clf.predict(X))
    
    print("Calculated Prediction is: ")
    res = np.matmul(X, clf.feature_log_prob_.T) + clf.class_log_prior_
    print(res.argmax(axis=1) + 1)
    
    

In [67]:
X = np.random.randint(5, size=(6, 100))

In [73]:
y = np.array([1, 2, 3, 4, 5, 5])
y.shape
type(y)

numpy.ndarray

In [74]:
from sklearn.naive_bayes import MultinomialNB
clf = MultinomialNB()   

In [75]:
clf.fit(X, y)

MultinomialNB(alpha=1.0, class_prior=None, fit_prior=True)

In [76]:
print(clf.predict(X))

[1 2 3 4 5 5]


In [77]:
predict_compare(clf, X)

Prediction is: 
[1 2 3 4 5 5]
Calculated Prediction is: 
[1 2 3 4 5 5]
